version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run: gem update --system
      - run: gem install bundler
      - run: bundle update --bundler
